/**
 * command name: reload
 * description: clears cache generated by commands.
 * author: Amrit Pandey
 * dependencies: fs
 */

const fs = require('fs');

exports.run = (client, message, args) => {
  // collect all the command names whoes caches needs to be cleared.
  const commandNames = args;
  // relead commmand directory to find commands
  fs.readdir('./commands/', (err, commandFiles) => {
    commandNames.forEach((commandName) => {
      // if command exist clear cache
      if (commandFiles.indexOf(`${commandName}.js`) !== -1) {
        delete require.cache[require.resolve(`./${commandName}.js`)];
        message.channel.send(
          `:white_check_mark: Reloading *${commandName}* : **successful**`
        );
      } else
        message.channel.send(
          `:exclamation: Cannot reload command *${commandName}* : **command do not exist**`
        );
    });
  });
};
