module.exports = {
  su: {
    announce: {
      category: 'utility',
      description: 'makes an announcement on the channel',
      isEnabled: true
    }
  },
  gen: {
    help: {
      category: 'utility',
      description: 'display manual for a command',
      isEnabled: true
    },
    reload: {
      category: 'utility',
      description: 'clear cache generated by any command',
      isEnabled: true
    },
    define: {
      category: 'web',
      description: '',
      isEnabled: true
    }
  }
};
