module.exports = {
  su: {
    announce: {
      category: '🛠 utility',
      description: 'makes an announcement on the channel',
      usage: '<message>',
      isEnabled: true,
      permitLevel: 0
    },
    broadcast: {
      category: '🛠 utility',
      description: 'broadcast a message on every guild',
      usage: '<message>',
      isEnabled: true,
      permitLevel: 2
    }
  },
  gen: {
    help: {
      category: '🛠 utility',
      description: 'display manual for a command',
      usage: '<command name>',
      isEnabled: true
    },
    reload: {
      category: '🛠 utility',
      description: 'clear cache generated by any command',
      usage: '<command names>',
      isEnabled: true
    },
    define: {
      category: '🌐 web',
      description: 'provides definition for words from web',
      usage: '?wiki <search string>',
      isEnabled: true
    },
    news: {
      category: '🌐 web',
      description: 'latest headings from google news',
      usage: '<topic | term | category>',
      isEnabled: true
    },
    bot: {
      category: '🛠 utility',
      description: 'gets information about bot',
      usage: '<information type>',
      isEnabled: true
    },
    gupt: {
      category: '🎮 fun',
      description: 'send anonymous message to anyone(broken)',
      usage: '<user id> <message>',
      isEnabled: true
    },
    gif: {
      category: '🎮 fun',
      description: 'send a custom gif to the channel',
      usage: '<gif name>',
      isEnabled: true
    }
  }
};
