module.exports = {
  su: {
    announce: {
      category: '🛠 utility',
      description: 'makes an announcement on the channel',
      usage: '<message>',
      isEnabled: true
    }
  },
  gen: {
    help: {
      category: '🛠 utility',
      description: 'display manual for a command',
      usage: '<command name>',
      isEnabled: true
    },
    reload: {
      category: '🛠 utility',
      description: 'clear cache generated by any command',
      usage: '<command names>',
      isEnabled: true
    },
    define: {
      category: '🌐 web',
      description: 'provides definition for words from web',
      usage: '<search string>',
      isEnabled: true
    },
    bot: {
      category: '🛠 utility',
      description: 'gets information on bot',
      usage: '<information type>',
      isEnabled: true
    }
  }
};
